--to create blip (you can change coordinate, blip, name everything here)
Citizen.CreateThread(function()
    Dealer = AddBlipForCoord(vector3(-1607.47, -830.16, 10.08))
    SetBlipSprite (Dealer, 289)
    SetBlipDisplay(Dealer, 4)
    SetBlipScale  (Dealer, 0.75)
    SetBlipAsShortRange(Dealer, true)
    SetBlipColour(Dealer, 3)
    BeginTextCommandSetBlipName('STRING')
    AddTextComponentSubstringPlayerName('Gudang Pantai')
    EndTextCommandSetBlipName(Dealer)
end)

Citizen.CreateThread(function()
    Dealer = AddBlipForCoord(vector3(-43.81, -1236.47, 29.34))
    SetBlipSprite (Dealer, 289)
    SetBlipDisplay(Dealer, 4)
    SetBlipScale  (Dealer, 0.75)
    SetBlipAsShortRange(Dealer, true)
    SetBlipColour(Dealer, 3)
    BeginTextCommandSetBlipName('STRING')
    AddTextComponentSubstringPlayerName('Gudang Kota')
    EndTextCommandSetBlipName(Dealer)
end)